
DROP TABLE TBL_APLICACAO_MONITORAMENTO;
--Enviam para um sistema central
CREATE TABLE TBL_APLICACAO_MONITORAMENTO(
	cd_aplicacao          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cd_monitoramento        INTEGER NOT NULL,
	vlr_medido              NUMBER(10, 6) NOT NULL,
	vlr_minimo              NUMBER(10, 6) NOT NULL,
	vlr_maximo              NUMBER(10, 6) NOT NULL,
	vlr_aplicado            NUMBER(10, 6) NOT NULL,	
	cd_usuario_inclusao     INTEGER NOT NULL,
	dt_inclusao             TIMESTAMP NOT NULL	
);

DROP TABLE TBL_MONITORAMENTO;
--Enviam para um sistema central
CREATE TABLE TBL_MONITORAMENTO(
	cd_monitoramento    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	cd_cultura_produto_sensor          INTEGER NOT NULL,
	vlr_medido          NUMBER(10, 6) NOT NULL,
	dt_medicao			TIMESTAMP NOT NULL,
	cd_usuario_inclusao INTEGER NOT NULL,
	dt_inclusao         TIMESTAMP NOT NULL	
);

DROP TABLE TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO;
CREATE   TABLE TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO
(
    cd_cultura_produto_sensor_configuracao  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_cultura_produto_sensor       INTEGER       NOT NULL,    
    vlr_minimo                      NUMBER(10,6)  NOT NULL,
    vlr_maximo                      NUMBER(10,6)  NOT NULL,
    cd_usuario_inclusao             INTEGER       NOT NULL,
    dt_inclusao                     TIMESTAMP          NOT NULL
);

DROP TABLE TBL_CULTURA_PRODUTO_SENSOR;
CREATE   TABLE TBL_CULTURA_PRODUTO_SENSOR
(
    cd_cultura_produto_sensor  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_cultura            INTEGER       NOT NULL,
    cd_produto_sensor     INTEGER       NOT NULL,   
    cd_usuario_inclusao   INTEGER       NOT NULL,
    dt_inclusao           TIMESTAMP          NOT NULL
);


DROP TABLE TBL_PRODUTO_SENSOR;
CREATE TABLE TBL_PRODUTO_SENSOR(
	cd_produto_sensor       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cd_sensor               INTEGER NOT NULL,
	cd_produto              INTEGER NOT NULL,
	cd_status               NUMBER(1) DEFAULT 1 NOT NULL,
	cd_usuario_inclusao     INTEGER NOT NULL,
	dt_inclusao             DATE NOT NULL,
	cd_usuario_alteracao    INTEGER ,
	dt_alteracao            TIMESTAMP 
);



DROP TABLE TBL_CULTURA;
--O produtor planta diferentes culturas
CREATE TABLE TBL_CULTURA(
	cd_cultura             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nm_cultura              varchar(50) NOT NULL,
	cd_status               NUMBER(1) DEFAULT 1 NOT NULL,
	cd_usuario_inclusao     INTEGER NOT NULL,
	dt_inclusao             DATE NOT NULL,
	cd_usuario_alteracao    INTEGER,
	dt_alteracao            TIMESTAMP
);

DROP TABLE TBL_PRODUTO;
CREATE  TABLE TBL_PRODUTO(
	cd_produto             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nm_produto              VARCHAR(50) NOT NULL,
	cd_status               NUMBER(1) DEFAULT 1 NOT NULL,
	cd_usuario_inclusao     INTEGER NOT NULL,
	dt_inclusao             DATE NOT NULL,
	cd_usuario_alteracao    INTEGER,
	dt_alteracao            TIMESTAMP 
);



--Sensores coletam dados em tempo real 
DROP TABLE TBL_SENSOR;
CREATE  TABLE TBL_SENSOR(
	cd_sensor              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nm_sensor               varchar(50) NOT NULL,
	cd_status               NUMBER(1) DEFAULT 1 NOT NULL,
	cd_usuario_inclusao     INTEGER NOT NULL,
	dt_inclusao             DATE NOT NULL,
	cd_usuario_alteracao    INTEGER,
	dt_alteracao            TIMESTAMP 
);

ALTER TABLE TBL_PRODUTO_SENSOR  ADD  CONSTRAINT FK_TBL_PRODUTO_SENSOR_TBL_PRODUTO_CD_PRODUTO FOREIGN KEY(cd_produto)
REFERENCES TBL_PRODUTO (cd_produto);

ALTER TABLE TBL_PRODUTO_SENSOR   ADD  CONSTRAINT FK_TBL_PRODUTO_SENSOR_TBL_SENSOR_CD_SENSOR FOREIGN KEY(cd_sensor)
REFERENCES TBL_SENSOR (cd_sensor);

ALTER TABLE TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO  ADD  CONSTRAINT FK_TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO_TBL_CULTURA_PRODUTO_SENSOR_cd_cultura_produto_sensor FOREIGN KEY(cd_cultura_produto_sensor)
REFERENCES TBL_CULTURA_PRODUTO_SENSOR (cd_cultura_produto_sensor);

ALTER TABLE TBL_CULTURA_PRODUTO_SENSOR  ADD  CONSTRAINT FK_TBL_CULTURA_PRODUTO_SENSOR_TBL_PRODUTO_SENSOR_CD_PRODUTO_SENSOR FOREIGN KEY(cd_produto_sensor)
REFERENCES TBL_PRODUTO_SENSOR (cd_produto_sensor);

ALTER TABLE TBL_CULTURA_PRODUTO_SENSOR  ADD  CONSTRAINT FK_TBL_CULTURA_PRODUTO_SENSOR_TBL_CULTURA_cd_cultura FOREIGN KEY(cd_cultura)
REFERENCES TBL_CULTURA (cd_cultura);


ALTER TABLE TBL_MONITORAMENTO  ADD  CONSTRAINT FK_TBL_MONITORAMENTO_TBL_CULTURA_PRODUTO_SENSOR_CD_CULTURA_PRODUTO_SENSOR FOREIGN KEY(cd_cultura_produto_sensor)
REFERENCES TBL_CULTURA_PRODUTO_SENSOR (cd_cultura_produto_sensor);


ALTER TABLE TBL_APLICACAO_MONITORAMENTO  ADD  CONSTRAINT FK_TBL_APLICACAO_MONITORAMENTO_TBL_MONITORAMENTO_CD_MONITORAMENTO FOREIGN KEY(cd_monitoramento)
REFERENCES TBL_MONITORAMENTO (cd_monitoramento);


INSERT INTO TBL_CULTURA (nm_cultura, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'Café', 1, 1, SYSDATE, NULL, NULL);
INSERT INTO TBL_CULTURA (nm_cultura, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'Cana de açucar', 1, 1, SYSDATE, NULL, NULL);

INSERT INTO TBL_PRODUTO (nm_produto, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'Agua', 1, 1, SYSDATE, NULL, NULL);
INSERT INTO TBL_PRODUTO (nm_produto, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'PH', 1, 1, SYSDATE, NULL, NULL);
INSERT INTO TBL_PRODUTO (nm_produto, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'Luz', 1, 1, SYSDATE, NULL, NULL);

INSERT INTO TBL_SENSOR  (nm_sensor, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'Sensor de Umidade', 1, 1, SYSDATE, NULL, NULL);
INSERT INTO TBL_SENSOR  (nm_sensor, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'Sensor de Potassio', 1, 1, SYSDATE, NULL, NULL);
INSERT INTO TBL_SENSOR  (nm_sensor, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'Sensor de Fosforo', 1, 1,SYSDATE, NULL, NULL);
INSERT INTO TBL_SENSOR  (nm_sensor, cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao) VALUES ( 'Sensor de Luminosidade', 1, 1,SYSDATE, NULL, NULL);


INSERT INTO TBL_PRODUTO_SENSOR (cd_sensor ,cd_produto,cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao)  VALUES ( 1, 1, 1,1,SYSDATE, NULL, NULL);
INSERT INTO TBL_PRODUTO_SENSOR (cd_sensor ,cd_produto,cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao)  VALUES ( 2, 2, 1,1,SYSDATE, NULL, NULL);
INSERT INTO TBL_PRODUTO_SENSOR (cd_sensor ,cd_produto,cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao)  VALUES ( 3, 2, 1,1,SYSDATE, NULL, NULL);
INSERT INTO TBL_PRODUTO_SENSOR (cd_sensor ,cd_produto,cd_status, cd_usuario_inclusao, dt_inclusao,cd_usuario_alteracao, dt_alteracao)  VALUES ( 4, 3, 1,1,SYSDATE, NULL, NULL);


INSERT INTO TBL_CULTURA_PRODUTO_SENSOR (cd_cultura, cd_produto_sensor , cd_usuario_inclusao,dt_inclusao) VALUES (1,1,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR (cd_cultura, cd_produto_sensor , cd_usuario_inclusao,dt_inclusao) VALUES (1,2,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR (cd_cultura, cd_produto_sensor , cd_usuario_inclusao,dt_inclusao) VALUES (1,3,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR (cd_cultura, cd_produto_sensor , cd_usuario_inclusao,dt_inclusao) VALUES (1,4,1,SYSDATE);

INSERT INTO TBL_CULTURA_PRODUTO_SENSOR (cd_cultura, cd_produto_sensor , cd_usuario_inclusao,dt_inclusao) VALUES (2,1,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR (cd_cultura, cd_produto_sensor , cd_usuario_inclusao,dt_inclusao) VALUES (2,2,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR (cd_cultura, cd_produto_sensor , cd_usuario_inclusao,dt_inclusao) VALUES (2,3,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR (cd_cultura, cd_produto_sensor , cd_usuario_inclusao,dt_inclusao) VALUES (2,4,1,SYSDATE);

INSERT INTO TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO (cd_cultura_produto_sensor, vlr_minimo, vlr_maximo, cd_usuario_inclusao,dt_inclusao) VALUES ( 1,25,53,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO (cd_cultura_produto_sensor, vlr_minimo, vlr_maximo, cd_usuario_inclusao,dt_inclusao) VALUES ( 2,23,53,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO (cd_cultura_produto_sensor, vlr_minimo, vlr_maximo, cd_usuario_inclusao,dt_inclusao) VALUES ( 3,15,53,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO (cd_cultura_produto_sensor, vlr_minimo, vlr_maximo, cd_usuario_inclusao,dt_inclusao) VALUES ( 4,35,93,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO (cd_cultura_produto_sensor, vlr_minimo, vlr_maximo, cd_usuario_inclusao,dt_inclusao) VALUES ( 5,15,3,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO (cd_cultura_produto_sensor, vlr_minimo, vlr_maximo, cd_usuario_inclusao,dt_inclusao) VALUES ( 6,45,73,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO (cd_cultura_produto_sensor, vlr_minimo, vlr_maximo, cd_usuario_inclusao,dt_inclusao) VALUES ( 7,15,53,1,SYSDATE);
INSERT INTO TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO (cd_cultura_produto_sensor, vlr_minimo, vlr_maximo, cd_usuario_inclusao,dt_inclusao) VALUES ( 8,45,53,1,SYSDATE);




SELECT * FROM TBL_SENSOR;
SELECT * FROM TBL_PRODUTO;
SELECT * FROM TBL_CULTURA;
SELECT * FROM TBL_PRODUTO_SENSOR;
SELECT * FROM TBL_CULTURA_PRODUTO_SENSOR;
SELECT * FROM TBL_MONITORAMENTO;
SELECT * FROM TBL_CULTURA_PRODUTO_SENSOR_CONFIGURACAO;
SELECT * FROM TBL_APLICACAO_MONITORAMENTO;
commit;

